# Generated by Django 4.0.2 on 2022-03-16 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veteran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Surname_Name', models.CharField(max_length=200)),
                ('text', models.CharField(max_length=800)),
            ],
        ),
    ]
