# Generated by Django 4.0.2 on 2022-03-16 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_articles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новость'},
        ),
        migrations.RemoveField(
            model_name='articles',
            name='date',
        ),
    ]
