# Generated by Django 4.0.2 on 2022-03-17 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_menprize'),
    ]

    operations = [
        migrations.CreateModel(
            name='Men',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('photo', models.CharField(max_length=10000)),
                ('text', models.CharField(max_length=10000)),
            ],
        ),
    ]
