# Generated by Django 4.0.2 on 2022-03-27 18:46

from django.db import migrations, models
import main.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_articles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mvideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mcountry', models.CharField(max_length=50)),
                ('mtext', models.TextField(max_length=5000)),
                ('msportsmen', models.CharField(max_length=50)),
                ('mcaption', models.CharField(max_length=100)),
                ('mvideo', models.FileField(upload_to='video/%y', validators=[main.validators.file_size])),
            ],
        ),
    ]
